<b>operator</b>: [% operator %]<br />
<b>id</b>: [% id %]<br />
<b>payments</b>: [% payments %]<br />
<b>title</b>: [% title %]<br />
<b>insertdatetime</b>: [% insertdatetime %]<br />
<b>available</b>: [% available %]<br />
<b>startdate</b>: [% startdate %]<br />
<b>enddate</b>: [% enddate %]<br />
<b>price</b>: [% price %]<br />
<b>currency</b>: [% currency %]<br />
<b>unit</b>: [% unit %]<br />
<b>expiry</b>: [% expiry %]<br />
<b>minutes</b>: [% minutes %]<br />
<b>messages</b>: [% messages %]<br />
<b>datasize</b>: [% datasize %]<br />
<b>internet</b>: [% internet %]<br />
<b>description</b>: [% description %]<br />